name: smf_workspace
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

workspace:
  - packages/smf_hooks
  - packages/smf_engine
  - packages/smf_apple
  - packages/smf_cli

dev_dependencies:
  melos: ^8.2.2

melos:
  repository: https://github.com/Ventairy/smf
  scripts:
    format:
      run: dart format .
    format:check:
      run: dart format --output=none --set-exit-if-changed .
    analyze:
      run: dart analyze --fatal-infos
    test:
      exec:
        command: dart test
        concurrency: 1
      packageFilters:
        dirExists: test
    generate:
      exec:
        command: dart run build_runner build
        concurrency: 1
      packageFilters:
        dependsOn: build_runner
    publish:dry-run:
      exec:
        command: dart pub publish --dry-run
        concurrency: 1
